name: trial
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  curved_navigation_bar: ^1.0.6
  animated_text_kit: ^4.2.1
  model_viewer_plus: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Appicon.jpeg"
  adaptive_background_color: "#ffffff"
  adaptive_icon_foreground: "assets/images/Appicon.jpeg"
  adaptive_icon_background: "#ffffff"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section.
  assets:
    - assets/
    - assets/images/

  # To add custom fonts to your application, add a fonts section.
  fonts:
    - family: JosefinSans_Bold
      fonts:
        - asset: assets/fonts/JosefinSans-Bold.ttf

    - family: JosefinSans_BoldItalic
      fonts:
        - asset: assets/fonts/JosefinSans-BoldItalic.ttf

    - family: JosefinSans_Italic
      fonts:
        - asset: assets/fonts/JosefinSans-Italic.ttf

    - family: JosefinSans_Medium
      fonts:
        - asset: assets/fonts/JosefinSans-Medium.ttf

    - family: JosefinSans_MediumItalic
      fonts:
        - asset: assets/fonts/JosefinSans-MediumItalic.ttf

    - family: JosefinSans_Regular
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf

    - family: JosefinSans_SemiBold
      fonts:
        - asset: assets/fonts/JosefinSans-SemiBold.ttf

